### ISSUE TITLE
API 엔드포인트 숨기기 제안

### ISSUE THREAD

**Issue by minsoo-web** [Memorip/memorip-frontend#16]
안녕하세요, 깃헙을 둘러보다 우연히 알게된 오픈소스에 개선하면 좋을 것 같은 사항이 있어 제안드리고자 이슈 남기게 되었습니다!
단순히 제안의 내용이니 가볍게 읽어주시면 감사하겠습니다.

지금 src/envs/index.ts 파일에 보면 endpoint 가 그대로 노출되어 있습니다. .env 파일을 사용하고 계시니, API url을 숨기시는 게 좋을 것 같습니다.
백엔드 repo도 open source 이다보니, DB 접근 방식에 대해서도 충분히 유추가 가능하고, 스웨거 쓰겠지 라는 생각에 swagger-ui path 로 접근해보니 swagger 도 확인해볼 수 있습니다. public 으로 repo를 관리할 때 신경써야 하는 부분이니, 개선하면 좋을 것 같아 제안 드립니다! next의 설정을 통해 우회해서 api를 요청하면 네트워크 탭으로도 엔드포인트를 볼 수 없으니 그렇게 적용해보는 것은 어떨까요?!

**Comment by hyungwookchoi** [comment]
안녕하세요! 말씀하신대로 개선해서 적용하려고 합니다. 제안 감사합니다 🙂
